export const SET_FETCHING_IN_PROCESS = "COMMON/SET_FETCHING_IN_PROCESS";
export const SET_ROLE = "COMMON/SET_ROLE";
export const SET_SERVER_ERROR = "COMMON/SET_SERVER_ERROR";

export const AUTH_SET_USER_IS_DOCTOR = "AUTH/SET_USER_IS_DOCTOR";
export const AUTH_SET_USER_AUTH = "AUTH/SET_USER_AUTH";

export const EXAMINATION_SET_EXAMINATIONS = "RECIPES/SET_EXAMINATIONS";
export const EXAMINATION_SET_EXAMINATIONS_COUNT = "RECIPES/SET_EXAMINATIONS_COUNT";
